# Generated by Django 5.2.4 on 2025-08-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
