# Generated by Django 3.1.4 on 2025-08-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
