# Generated by Django 3.1.4 on 2025-07-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tblcomtact',
            new_name='tblcontact',
        ),
    ]
