# Generated by Django 5.2.4 on 2025-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20250726_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=70)),
                ('picture', models.ImageField(null=True, upload_to='static/gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='tblcontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tblgallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tblgallery',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/gallery/'),
        ),
    ]
