# Generated by Django 3.1.4 on 2025-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tblteam_alter_tblcontact_id_alter_tblgallery_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
                ('regdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblregister',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/userpic/')),
                ('batch', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('regdate', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tblcontact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tblgallery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tblteam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
