# Generated by Django 3.1.4 on 2025-07-30 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20250729_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='softkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('soft_info', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='static/softthumb/')),
                ('download_link', models.CharField(max_length=200, null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='regdate',
        ),
        migrations.AddField(
            model_name='batch',
            name='batchname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='static/category')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.batch')),
            ],
        ),
    ]
