# Generated by Django 5.2.4 on 2025-07-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_batch_id_alter_softkit_id_alter_tblcontact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='static/category/')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.batch')),
            ],
        ),
        migrations.DeleteModel(
            name='tblcat',
        ),
    ]
