# Generated by Django 5.2.4 on 2025-07-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_category_delete_tblcat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
