# Generated by Django 5.2.4 on 2025-07-30 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecturecat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='static/category/')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.batch')),
            ],
        ),
    ]
