# Generated by Django 5.2.4 on 2025-07-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_lecturecat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lecturecat',
            new_name='tblcategory',
        ),
    ]
