# Generated by Django 5.2.4 on 2025-07-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_lecturecat_tblcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblregister',
            old_name='address',
            new_name='add',
        ),
    ]
