# Generated by Django 5.2.4 on 2025-08-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tag_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
