# Generated by Django 5.2.4 on 2025-08-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_tblregister_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregister',
            name='batch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
