# Generated by Django 5.2.4 on 2025-08-01 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_tblregister_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregister',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.batch'),
        ),
    ]
