# Generated by Django 5.2.4 on 2025-08-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_tblregister_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcategory',
            old_name='batch_name',
            new_name='batchname',
        ),
    ]
