# Generated by Django 5.2.4 on 2025-08-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_rename_batch_name_tblcategory_batchname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcategory',
            old_name='batchname',
            new_name='batch_name',
        ),
    ]
