# Generated by Django 5.2.4 on 2025-08-01 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_rename_batchname_tblcategory_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='lacvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('discription', models.TextField(null=True)),
                ('vlink', models.CharField(max_length=200, null=True)),
                ('posted_date', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.batch')),
                ('tblcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tblcategory')),
            ],
        ),
        migrations.CreateModel(
            name='mytask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('taskinfo', models.TextField(null=True)),
                ('taskfile', models.FileField(blank=True, null=True, upload_to='static/task/')),
                ('posted_date', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.batch')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('notesinfo', models.TextField(null=True)),
                ('posted_date', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.batch')),
            ],
        ),
    ]
