# Generated by Django 5.2.4 on 2025-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_lacvideo_mytask_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lacvideo',
            name='vlink',
            field=models.FileField(null=True, upload_to='static/lectures/'),
        ),
    ]
