# Generated by Django 5.2.4 on 2025-08-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_alter_lacvideo_vlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lacvideo',
            name='vlink',
            field=models.FileField(max_length=300, null=True, upload_to='static/lectures/'),
        ),
    ]
