# Generated by Django 5.2.4 on 2025-08-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_alter_lacvideo_vlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to='static/notes/'),
        ),
    ]
