# Generated by Django 5.2.4 on 2025-08-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_notes_notesfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='softkit',
            new_name='software',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='download_link',
            new_name='downloadlink',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='posted_date',
            new_name='posteddate',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='soft_info',
            new_name='softinfo',
        ),
    ]
