# Generated by Django 5.2.4 on 2025-08-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_rename_softkit_software_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='submittedtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('tid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('upload_task', models.FileField(blank=True, null=True, upload_to='static/submitted/')),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='software',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='softthumb/'),
        ),
    ]
