# Generated by Django 5.2.4 on 2025-08-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_submittedtask_alter_software_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lacvideo',
            new_name='mylecture',
        ),
    ]
