# Generated by Django 3.1.4 on 2025-08-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_auto_20250803_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batchname',
            new_name='batch_name',
        ),
        migrations.RenameField(
            model_name='tblcategory',
            old_name='pic',
            new_name='picture',
        ),
    ]
