# Generated by Django 3.1.4 on 2025-08-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_auto_20250803_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylecture',
            name='vlink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
