# Generated by Django 3.1.4 on 2025-08-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_auto_20250803_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylecture',
            old_name='discription',
            new_name='video_info',
        ),
    ]
