# Generated by Django 3.1.4 on 2025-08-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_auto_20250803_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='taskinfo',
            new_name='task_info',
        ),
        migrations.AlterField(
            model_name='mytask',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.batch'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='posted_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
